name: unittests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * 1"

defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 4
    strategy:
      fail-fast: false
      matrix:
        container:
          - python:3.6-slim
          - python:3.7-slim
          - python:3.8-slim
          - python:3.9-slim
          - pypy:3.6-slim

    container: ${{ matrix.container }}


    steps:
    - uses: actions/checkout@v1
    
    - name: Choose python command
      id: command
      run: |
        if [[ "${{ matrix.container }}" = pypy* ]] ;
        then
          echo "::set-output name=python::pypy3"
        else
          echo "::set-output name=python::python"
        fi

    - name: Install package
      run: |
        ${{ steps.command.outputs.python }} -m pip install --upgrade pip
        pip install -e .[test]

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pip install pytest-cov
        pytest --cov=draughts --cov-report=xml
        
    - name: Upload coverage  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
